"""Resource / API layer: a thin, declarative resource abstraction on WebRouter.

This module does **not** create a second API framework.  It layers a small,
LLM-friendly declaration surface on top of the existing Betrayer abstractions
(:class:`~betrayer.web.routing.WebRouter`, :class:`~betrayer.web.request.Request`,
:class:`~betrayer.web.response.ApiResponse`, :class:`~betrayer.web.context.WebContext`)
so an application can define resources without inventing a parallel route
system.

What is offered
---------------
* :class:`ApiResource` -- a base class that declares endpoints
  (``method + path + handler``) and registers them on any ``WebRouter``.
* :class:`CrudApiResource` -- one shared CRUD implementation
  (``GET/POST/GET <id>/PUT <id>/DELETE <id>``) that delegates to a service,
  so every resource uses the same flow instead of per-resource special cases.
* :class:`ResourceRegistry` -- collects routers/resources and mounts them all
  on one :class:`~betrayer.web.adapter.FlaskAdapter`.
* :func:`register_web_router` -- mount an existing ``WebRouter`` (for example
  one generated by ``bet make resource`` / ``bet make crud``) on an adapter.

Flow preserved:::

    HTTP Request -> Resource (route handler) -> Service -> Repository/Data

Resources stay thin: they resolve a service through ``WebContext.resolve()``
(the Task 02 container) and never take over business logic.
"""

from __future__ import annotations

from typing import Any, Callable, Dict, Iterable, List, Optional, Sequence, Tuple, Union

from betrayer.auth.authorization import authorize
from betrayer.web.context import WebContext
from betrayer.web.pagination import (
    PaginatedResult,
    PaginationMetadata,
    PaginationParams,
    paginate_sequence,
    parse_pagination,
)
from betrayer.web.request import Request
from betrayer.web.response import ApiResponse, Response
from betrayer.web.routing import Route, WebRouteRegistry, WebRouter
from betrayer.web.validation import Schema, ValidationResult, validate as _validate

__all__ = [
    "ApiResource",
    "CrudApiResource",
    "ResourceRegistry",
    "register_web_router",
]


def _dumps(item: Any) -> Any:
    """Serialize ``item`` to a plain dict when it exposes ``to_dict``."""
    if hasattr(item, "to_dict"):
        value = item.to_dict()
        return value() if callable(value) else value
    return item


def _collection_response(
    items: Sequence[Any],
    *,
    resource: str,
    pagination: Optional[PaginationMetadata] = None,
) -> Response:
    payload = [_dumps(item) for item in items]
    meta: Dict[str, Any] = {"resource": resource, "count": len(payload)}
    if pagination is not None:
        meta["pagination"] = pagination.to_dict()
    return ApiResponse.success(data=payload, meta=meta)


def _coerce_paginated(raw: Any, params: PaginationParams) -> PaginatedResult:
    """Normalise a ``service.paginate()`` result into a ``PaginatedResult``.

    Accepted shapes:

    * a :class:`~betrayer.web.pagination.PaginatedResult` (canonical);
    * a ``(items, total)`` pair (``items`` a sequence, ``total`` an int);
    * a mapping with ``items``/``data`` and an optional ``total``.

    Anything else raises a structured ``TypeError`` so misuse is caught
    early instead of producing a broken envelope at runtime.
    """
    from betrayer.web.exceptions import WebAdapterError

    if isinstance(raw, PaginatedResult):
        return raw
    if isinstance(raw, tuple) and len(raw) == 2:
        items, total = raw
        return PaginatedResult(
            items=items,
            metadata=PaginationMetadata.from_params(params, int(total)),
        )
    if isinstance(raw, dict):
        items = raw.get("items", raw.get("data"))
        if items is None:
            raise WebAdapterError(
                message=(
                    "service.paginate() mapping must carry 'items' or 'data'"
                ),
                code="SERVICE_PAGINATE_INVALID",
                context={"received": list(raw)},
            )
        total = raw.get("total")
        if total is None:
            total = len(items)
        return PaginatedResult(
            items=items,
            metadata=PaginationMetadata.from_params(params, int(total)),
        )
    raise WebAdapterError(
        message=(
            "service.paginate() must return a PaginatedResult, an (items, "
            "total) pair or a mapping with 'items'/'total'"
        ),
        code="SERVICE_PAGINATE_INVALID",
        context={"received": type(raw).__name__},
    )


class ApiResource:
    """Declarative collection of HTTP endpoints bound to one WebRouter.

    Subclasses declare their endpoints by overriding :meth:`endpoints` (or by
    passing ``routes`` to the constructor) and register on any
    :class:`~betrayer.web.routing.WebRouter`::

        class HealthResource(ApiResource):
            name = "health"
            prefix = "/api/v1"

            def endpoints(self):
                return [
                    ("GET", "/ping", self.ping),
                ]

            async def ping(self, request, context):
                return ApiResponse.success({"status": "ok"})

        router = WebRouter(name="app")
        HealthResource().register(router)   # -> GET /api/v1/health/ping

    Handlers use the documented ``handler(request, context) -> Response``
    signature and may be sync or async.  The resource never touches Flask.
    """

    #: Resource identifier used for the default path base (``/{name}``),
    #: the router name and the default service key (``{name}_service``).
    name: str = "resource"

    #: Optional path prefix, e.g. ``"/api/v1"`` (joined without a double slash).
    prefix: str = ""

    #: Declarative ``(method, path, handler)`` triples.  Pass ``None`` and
    #: override :meth:`endpoints` for the explicit form.
    routes: Tuple[Tuple[str, str, Callable[..., Any]], ...] = ()

    #: Optional request validation schema (a
    #: :class:`~betrayer.web.validation.Schema` instance, a ``Schema``
    #: subclass, or a raw field mapping).  When set, the CRUD handlers parse
    #: the JSON body once and validate it *before* calling the service.
    schema: Any = None

    #: When ``True``, the resource refuses anonymous requests with 401
    #: ``UNAUTHENTICATED`` before calling the service.
    #: The check is done in every endpoint handler of this resource
    #: (both the default CRUD handlers and custom ``endpoints()``).
    #: Set ``authentication_required = True`` on subclasses to protect
    #: every endpoint at once, or check ``request.user.is_anonymous``
    #: in individual handlers.
    authentication_required: bool = False

    #: When ``True`` the default handlers run an authorization check through
    #: the container ``"authorizer"`` service (canonical DI key) via
    #: :func:`betrayer.auth.authorize` **after** authentication.  A denial
    #: raises 403 ``FORBIDDEN`` (structured error envelope); routes without
    #: the flag are untouched.
    authorization_required: bool = False

    #: Default action passed to the authorizer (e.g. ``"view"``, ``"update"``).
    authorization_action: str = "access"

    #: Optional per-method action overrides, e.g.
    #: ``{"POST": "create", "PUT": "update", "DELETE": "delete"}``.
    authorization_actions: Optional[Dict[str, str]] = None

    #: Optional path parameter whose value is passed to the authorizer as
    #: ``resource`` (``None`` passes no resource object).
    authorization_resource_key: Optional[str] = None

    #: Optional rate limit configuration for every endpoint of this resource.
    #: When set (a ``RateLimit`` instance), the
    #: :class:`~betrayer.ratelimit.RateLimitMiddleware` enforces the limit.
    #: Resources without ``rate_limit`` are **not** rate limited.
    #: Per-route overrides are possible through the route's metadata dict.
    #:
    #: Usage::
    #:
    #:     from betrayer.ratelimit import RateLimit
    #:
    #:     class ProductResource(CrudApiResource):
    #:         rate_limit = RateLimit(limit=100, window=60)
    rate_limit: Any = None

    #: Optional HTTP cache TTL in seconds for ``GET``/``HEAD`` responses.
    #: When set (an ``int`` or a ``CachePolicy`` instance), the
    #: :class:`~betrayer.cache.WebCacheMiddleware` caches responses for the
    #: specified duration.  Resources without ``cache_ttl`` are **not**
    #: cached.  Per-route overrides are possible through the route's
    #: metadata dict.
    #:
    #: Usage::
    #:
    #:     from betrayer.cache import CachePolicy
    #:
    #:     class ProductResource(CrudApiResource):
    #:         cache_ttl = 60                    # simple int
    #:         cache_ttl = CachePolicy(ttl=60)   # explicit policy
    cache_ttl: Any = None

    #: When ``True`` the collection (``GET {base}``) handler reads ``page`` /
    #: ``per_page`` query parameters and returns ``meta.pagination`` metadata
    #: next to the items.  The service is given ``page``/``per_page`` keywords
    #: when it accepts them (optional ``paginate()`` method); otherwise the
    #: collection is paginated in memory.  Endpoints without the flag are
    #: completely untouched.
    pagination: bool = False

    def __init__(
        self,
        *,
        service: Any = None,
        service_key: Optional[str] = None,
    ) -> None:
        self.service = service
        self._service_key = service_key

    # -- declaration ---------------------------------------------------
    @property
    def service_key(self) -> str:
        """Container key the resource resolves its service from."""
        if self._service_key:
            return self._service_key
        return f"{self.name}_service"

    @property
    def base_path(self) -> str:
        """Default path base: ``{prefix}/{name}`` (never a trailing slash)."""
        parts = [str(self.prefix or "").strip("/"), self.name]
        return "/" + "/".join(part for part in parts if part)

    def endpoints(self) -> Sequence[Tuple[str, str, Callable[..., Any]]]:
        """Return ``(method, path, handler)`` endpoint declarations.

        Paths are relative to :attr:`base_path` (``""`` = the collection,
        ``"/<id>"`` = one item).  Override this in subclasses; the default
        returns the class-level :attr:`routes` triples.
        """
        return list(self.routes)

    # -- registration --------------------------------------------------
    def register(
        self,
        router: WebRouter,
        *,
        prefix: Optional[str] = None,
    ) -> List[Route]:
        """Register every endpoint on ``router``; returns the created routes.

        ``prefix`` overrides :attr:`prefix` for this call, so the same
        resource can be mounted at several bases without redefining it.
        """
        base = "/" + "/".join(
            part
            for part in [str(prefix or self.prefix or "").strip("/"), self.name]
            if part
        )
        created: List[Route] = []
        for method, path, handler in self.endpoints():
            full = base + str(path)
            meta: Dict[str, Any] = {}
            if self.rate_limit is not None:
                from betrayer.ratelimit.limit import RateLimit as _RateLimit
                if isinstance(self.rate_limit, _RateLimit):
                    meta["rate_limit"] = self.rate_limit
            if self.cache_ttl is not None:
                from betrayer.cache.policy import CachePolicy as _CachePolicy
                if isinstance(self.cache_ttl, _CachePolicy):
                    meta["cache_policy"] = self.cache_ttl
                elif isinstance(self.cache_ttl, (int, float)):
                    meta["cache_policy"] = _CachePolicy(ttl=self.cache_ttl)
            created.append(
                router.add(method, full, handler, module=self.name, metadata=meta)
            )
        return created

    def resource_router(self) -> WebRouter:
        """A dedicated ``WebRouter`` for this resource (already registered)."""
        router = WebRouter(name=self.name)
        self.register(router)
        return router

    # -- service resolution -------------------------------------------
    def resolve_service(self, context: WebContext) -> Any:
        """Resolve the service from the container (unless injected).

        ``self.service`` when given wins; otherwise the service is resolved
        from the request ``WebContext`` under :attr:`service_key`.  The
        resolution is lazy so a resource can be unit tested with a plain
        stub instead of a full application.
        """
        if self.service is not None:
            return self.service
        return context.resolve(self.service_key)

    # -- request validation pipeline (Task 11) ------------------------
    def request_schema(self) -> Any:
        """Return the resolved validation ``Schema`` (or ``None``).

        ``self.schema`` (or a ``schema_key`` service on the container) may be a
        :class:`~betrayer.web.validation.Schema` instance, a ``Schema``
        subclass or a raw field mapping; it is normalised here so handlers
        never branch on its shape.
        """
        raw = self.schema
        if raw is None:
            return None
        if isinstance(raw, Schema):
            return raw
        if isinstance(raw, type) and issubclass(raw, Schema):
            return raw()
        if isinstance(raw, dict):
            return Schema(raw)
        from betrayer.web.exceptions import WebAdapterError

        raise WebAdapterError(
            message=(
                "Resource.schema must be a Schema, a Schema subclass or a field "
                f"mapping, got {type(raw).__name__}"
            ),
            code="RESOURCE_SCHEMA_INVALID",
            context={"resource": self.name},
        )

    def validate_request(
        self,
        request: Request,
        context: Optional[WebContext] = None,
        *,
        partial: bool = False,
    ) -> ValidationResult:
        """Parse the body once, validate it, return the structured result.

        The JSON body is read through :meth:`json_body` (memoised, so parsing
        happens exactly once).  When a :attr:`schema` is declared the body is
        validated against it; the :class:`ValidationResult` is attached to the
        ``WebContext`` (``context.validation``) so the Service can read it too.

        An invalid body raises the framework ``ValidationError`` (422
        ``VALIDATION_FAILED``) carrying the structured field errors, so the
        service is never called.
        """
        body = self.json_body(request)
        result = _validate(self.request_schema(), body, partial=partial)
        if context is not None:
            context.set_validation(result)
        result.raise_if_invalid()
        return result

    def validated_body(
        self,
        request: Request,
        context: Optional[WebContext] = None,
        *,
        partial: bool = False,
    ) -> dict:
        """Validated, cleaned payload ready to hand to the service."""
        return self.validate_request(request, context, partial=partial).data

    # -- request/response helpers (thin, no business logic) -----------
    @staticmethod
    def require_authentication(request: Any) -> None:
        """Raise :class:`~betrayer.auth.UnauthenticatedError` when the request
        has no authenticated identity.

        Use this in custom endpoint handlers when :attr:`authentication_required`
        is not set on the class::

            async def my_handler(self, request, context):
                self.require_authentication(request)
                # ... authenticated-only logic ...

        The check reads ``request.user.is_anonymous`` which the
        :class:`~betrayer.auth.AuthenticationMiddleware` sets on every
        request (it is always an :class:`~betrayer.auth.Identity` or
        :class:`~betrayer.auth.AnonymousIdentity`).
        """
        user = getattr(request, "user", None)
        if user is None or getattr(user, "is_anonymous", True):
            from betrayer.auth.errors import UnauthenticatedError

            raise UnauthenticatedError(
                message="Authentication is required to access this resource",
            )

    @staticmethod
    def param(request: Request, name: str, *, cast: Callable[[Any], Any] = None) -> Any:
        """Return a path parameter, optionally coerced via ``cast``."""
        value = request.param(name)
        if cast is not None and value is not None:
            return cast(value)
        return value

    @staticmethod
    def query(request: Request, name: str, default: Any = None) -> Any:
        """Return a single query parameter (``default`` when absent)."""
        return request.get_query(name, default)

    @staticmethod
    def json_body(request: Request) -> dict:
        """Return the request JSON body as a dict.

        Raises :class:`~betrayer.web.exceptions.BadRequestError` when the
        body is missing, not JSON, or not a JSON object -- so handlers never
        have to repeat that check.
        """
        from betrayer.web.exceptions import BadRequestError

        body = request.json
        if body is None:
            raise BadRequestError(
                message="Request body must be a JSON object",
                code="BAD_REQUEST",
            )
        if not isinstance(body, dict):
            raise BadRequestError(
                message="Request body must be a JSON object",
                code="BAD_REQUEST",
                context={"content_type": request.content_type},
            )
        return body

    def require_fields(self, request: Request, *names: str) -> dict:
        """Validate that ``names`` are present in the JSON body.

        Returns the body (a dict).  Raises
        :class:`~betrayer.web.exceptions.ValidationError` (422) listing the
        missing fields, using the status code the Betrayer web layer maps a
        validation failure to.
        """
        from betrayer.web.exceptions import ValidationError

        body = self.json_body(request)
        missing = [name for name in names if name not in body]
        if missing:
            raise ValidationError(
                message=f"Missing required field(s): {', '.join(missing)}",
                errors=[{"field": name, "required": True} for name in missing],
            )
        return body

    def paginated_collection(
        self,
        request: Request,
        context: WebContext,
        *,
        resource: Optional[str] = None,
    ) -> Response:
        """Build a paginated collection response for ``GET {base}``.

        Reads and validates ``page`` / ``per_page`` through
        :func:`~betrayer.web.pagination.parse_pagination`, asks the resolved
        service for the page, and returns the standard collection envelope
        with ``meta.pagination`` metadata::

            {
              "success": true,
              "data": [...],
              "meta": {"resource": "product", "count": 20,
                       "pagination": {"page": 2, "per_page": 20,
                                      "total": 135, "total_pages": 7}}
            }

        The service may expose a canonical ``paginate(page=, per_page=)``
        method (returning a :class:`~betrayer.web.pagination.PaginatedResult`
        or a ``(items, total)`` pair); otherwise the whole ``service.list()``
        collection is paginated in memory with
        :func:`~betrayer.web.pagination.paginate_sequence`.  Invalid
        parameters raise the framework ``ValidationError`` (422) through the
        existing validation pipeline.
        """
        params = parse_pagination(request)
        service = self.resolve_service(context)
        result = self._paginate_service(service, params)
        return _collection_response(
            result.items,
            resource=resource or self.name,
            pagination=result.metadata,
        )

    @staticmethod
    def _paginate_service(service: Any, params: PaginationParams) -> PaginatedResult:
        """Ask ``service`` for one page; fall back to in-memory pagination.

        Priority: a canonical ``service.paginate(page=..., per_page=...)``
        (returns a ``PaginatedResult`` or a ``(items, total)`` pair), then a
        ``service.list(page=..., per_page=...)`` that supports pagination
        keywords, then in-memory slicing of ``service.list()``.

        The fallback keeps ``meta.pagination.total`` truthful (the whole
        collection count) while only the requested page is sliced.
        """
        paginate = getattr(service, "paginate", None)
        if callable(paginate):
            raw = paginate(page=params.page, per_page=params.per_page)
            return _coerce_paginated(raw, params)
        list_fn = getattr(service, "list", None)
        if callable(list_fn):
            try:
                items = list_fn(page=params.page, per_page=params.per_page)
            except TypeError:
                items = list_fn()
            return paginate_sequence(items, params)
        raise TypeError(
            f"Service {type(service).__name__} does not expose list()/paginate() "
            "needed for pagination"
        )

    @staticmethod
    def not_found(message: str = "Resource not found") -> None:
        """Raise :class:`~betrayer.web.exceptions.NotFoundError` (404)."""
        from betrayer.web.exceptions import NotFoundError

        raise NotFoundError(message)

    # -- authentication helper (Task 16.1) -----------------------------
    def _enforce_authentication(self, request: Any) -> None:
        """Check :attr:`authentication_required` and raise 401 if needed."""
        if self.authentication_required:
            self.require_authentication(request)

    # -- authorization helper (Task 16.2) -------------------------------
    def require_authorization(
        self,
        request: Any,
        context: Any,
        *,
        action: Optional[str] = None,
    ) -> None:
        """Run the authorization check for ``request`` (explicit form).

        Uses the container ``"authorizer"`` service (or
        ``self.authorizer`` when set) through
        :func:`betrayer.auth.authorize`; a denial raises 403
        ``FORBIDDEN`` with the structured error envelope.  Use this in
        custom handlers when :attr:`authorization_required` is not set::

            async def secret(self, request, context):
                self.require_authorization(request, context, action="view")
                ...

        Called automatically by the default CRUD handlers when the
        resource declares ``authorization_required = True``.
        """
        if not self.authorization_required and action is None:
            return
        resolved_action = (
            action
            or (self.authorization_actions or {}).get(getattr(request, "method", ""))
            or self.authorization_action
        )
        resource = None
        if self.authorization_resource_key:
            resource = request.param(str(self.authorization_resource_key))
        authorize(
            getattr(request, "user", None),
            resolved_action,
            resource=resource,
            context=context,
            authorizer=getattr(self, "authorizer", None),
        )

    def _enforce_authorization(self, request: Any, context: Any) -> None:
        """Run :meth:`require_authorization` when the flag is set (no-op otherwise)."""
        if self.authorization_required:
            self.require_authorization(request, context)

    # -- introspection ------------------------------------------------
    def to_dict(self) -> dict:
        """JSON friendly description of the declared resource."""
        return {
            "type": type(self).__name__,
            "name": self.name,
            "prefix": self.prefix,
            "base_path": self.base_path,
            "service_key": self.service_key,
            "endpoints": [
                {"method": method, "path": self.base_path + path}
                for method, path, _handler in self.endpoints()
            ],
        }

    describe = to_dict

    def __repr__(self) -> str:  # pragma: no cover - debugging aid
        return f"<{type(self).__name__} name={self.name!r} base={self.base_path!r}>"


class CrudApiResource(ApiResource):
    """One shared CRUD implementation for any service.

    Declares the standard REST endpoints and delegates every operation to the
    resolved service (``list``, ``get``, ``create``, ``update``, ``delete``),
    so no resource needs a per-resource copy of the flow::

        class ProductResource(CrudApiResource):
            name = "product"
            prefix = "/api/v1"

        router = WebRouter(name="app")
        ProductResource(service_key="product_service").register(router)

    Endpoints (paths are relative to ``{prefix}/{name}``)::

        GET    ""          -> service.list()        -> 200 [items]
        GET    "/<id>"     -> service.get(id)       -> 200 {item} | 404
        POST   ""          -> service.create(**body) -> 201 {item}
        PUT    "/<id>"     -> service.update(id, **body) -> 200 {item} | 404
        DELETE "/<id>"     -> service.delete(id)    -> 204 | 404

    ``PATCH`` is an alias handled by the same update flow: override
    :attr:`extra_methods` with ``[("PATCH", "/<id>", self.update_handler)]``
    if PATCH is needed; the default route set is deterministic and small.
    """

    #: Routes added on top of the standard CRUD set (e.g. PATCH).
    extra_methods: Tuple[Tuple[str, str, Callable[..., Any]], ...] = ()

    def endpoints(self) -> Sequence[Tuple[str, str, Callable[..., Any]]]:
        standard: List[Tuple[str, str, Callable[..., Any]]] = [
            ("GET", "", self.list_handler),
            ("GET", "/<id>", self.get_handler),
            ("POST", "", self.create_handler),
            ("PUT", "/<id>", self.update_handler),
            ("DELETE", "/<id>", self.delete_handler),
        ]
        return standard + list(self.extra_methods)

    # -- handlers (thin delegation, business logic stays in the service)
    async def list_handler(self, request: Request, context: WebContext) -> Response:
        """GET {base} -- list items through the service.

        When :attr:`pagination` is ``True`` the handler reads and validates
        ``page`` / ``per_page``, asks the service for one page and attaches
        ``meta.pagination``; otherwise it behaves exactly as before
        (``service.list()`` -> ``data`` + ``meta``).
        """
        self._enforce_authentication(request)
        self._enforce_authorization(request, context)
        if not self.pagination:
            service = self.resolve_service(context)
            return _collection_response(service.list(), resource=self.name)
        return self.paginated_collection(request, context, resource=self.name)

    async def get_handler(self, request: Request, context: WebContext) -> Response:
        """GET {base}/<id> -- fetch one item through the service."""
        self._enforce_authentication(request)
        self._enforce_authorization(request, context)
        service = self.resolve_service(context)
        identifier = request.param("id")
        item = service.get(identifier)
        if item is None:
            self.not_found(f"{self.name} not found")
        return ApiResponse.success(data=_dumps(item))

    async def create_handler(self, request: Request, context: WebContext) -> Response:
        """POST {base} -- validate then create an item through the service."""
        self._enforce_authentication(request)
        self._enforce_authorization(request, context)
        service = self.resolve_service(context)
        body = self.validated_body(request, context)
        item = service.create(**body)
        return ApiResponse.success(
            data=_dumps(item),
            status=201,
            meta={"resource": self.name},
        )

    async def update_handler(self, request: Request, context: WebContext) -> Response:
        """PUT {base}/<id> -- validate (partial) then update through the service."""
        self._enforce_authentication(request)
        self._enforce_authorization(request, context)
        service = self.resolve_service(context)
        identifier = request.param("id")
        body = self.validated_body(request, context, partial=True)
        item = service.update(identifier, **body)
        if item is None:
            self.not_found(f"{self.name} not found")
        return ApiResponse.success(data=_dumps(item))

    async def delete_handler(self, request: Request, context: WebContext) -> Response:
        """DELETE {base}/<id> -- delete an item through the service."""
        self._enforce_authentication(request)
        self._enforce_authorization(request, context)
        service = self.resolve_service(context)
        identifier = request.param("id")
        deleted = service.delete(identifier)
        if not deleted:
            self.not_found(f"{self.name} not found")
        return Response.no_content()

    def __init__(self, *, service: Any = None, service_key: Optional[str] = None) -> None:
        super().__init__(service=service, service_key=service_key)


def register_web_router(
    target: Any,
    router: WebRouter,
    *,
    prefix: str = "",
) -> Any:
    """Mount an existing ``WebRouter`` on a :class:`FlaskAdapter` (or Flask app).

    ``target`` is a :class:`~betrayer.web.adapter.FlaskAdapter` or a Flask
    application.  This is the compatibility helper for routers generated by
    ``bet make resource`` / ``bet make crud`` (Task 07)::

        from betrayer.web.adapter import FlaskAdapter
        from betrayer.web.resource import register_web_router
        from products.routes import router as product_router

        adapter = FlaskAdapter(application)          # build once
        register_web_router(adapter, product_router) # mount a generated router

    Returns the target adapter.
    """
    add = getattr(target, "add_router", None)
    if callable(add):
        add(router, prefix=prefix)
        return target
    # Plain Flask app: wrap it with an adapter and mount.
    from betrayer.web.adapter import FlaskAdapter

    adapter = FlaskAdapter(application=getattr(target, "application", None) or target, app=target)
    adapter.add_router(router, prefix=prefix)
    return adapter


class ResourceRegistry:
    """Collect resources/routers and mount them all on one adapter.

    Avoids route conflicts by letting the caller assign a ``prefix`` per
    entry; every item keeps its own ``WebRouter`` so registration order and
    ownership stay explicit.
    """

    def __init__(self, *, name: str = "resources") -> None:
        self.name = name
        self._entries: List[Tuple[Any, str]] = []

    # -- mutation -----------------------------------------------------
    def add(self, item: Any, *, prefix: str = "") -> "ResourceRegistry":
        """Register ``item`` (a ``WebRouter``, ``WebRouteRegistry`` or
        ``ApiResource``); ``prefix`` is prepended to every route path."""
        self._entries.append((item, (prefix or "").rstrip("/")))
        return self

    register = add

    def clear(self) -> None:
        """Drop every entry (used by tests/tooling)."""
        self._entries.clear()

    # -- access -------------------------------------------------------
    @property
    def entries(self) -> List[Tuple[Any, str]]:
        """Registered ``(item, prefix)`` pairs in registration order."""
        return list(self._entries)

    def routers(self) -> List[WebRouter]:
        """Resolve every entry into a ``WebRouter`` with its prefix applied.

        ``ApiResource`` entries are first registered on their own router;
        plain ``WebRouter`` entries are kept; ``WebRouteRegistry`` entries
        are wrapped.  Prefixes are baked into the returned routers.
        """
        routers: List[WebRouter] = []
        for item, prefix in self._entries:
            if isinstance(item, ApiResource):
                router = item.resource_router()
            elif isinstance(item, WebRouter):
                router = item
            elif isinstance(item, WebRouteRegistry):
                router = WebRouter(routes=item, name=item.name)
            else:
                raise TypeError(
                    "ResourceRegistry accepts ApiResource, WebRouter or "
                    f"WebRouteRegistry, got {type(item).__name__}"
                )
            if prefix:
                prefixed = WebRouter(name=f"{prefix}.{router.name}")
                for route in router.routes.list():
                    prefixed.add(
                        route.method,
                        f"{prefix}{route.path}",
                        route.handler,
                        name=route.endpoint,
                        module=route.module,
                        middleware=list(route.middleware),
                        metadata=dict(route.metadata),
                    )
                router = prefixed
            routers.append(router)
        return routers

    def merge(self, adapter: Any) -> Any:
        """Mount every router on ``adapter`` (a ``FlaskAdapter``)."""
        for router in self.routers():
            adapter.add_router(router)
        return adapter

    # -- introspection ------------------------------------------------
    def to_dict(self) -> dict:
        """JSON friendly snapshot of the registry."""
        return {
            "name": self.name,
            "entries": [
                {
                    "type": type(item).__name__,
                    "prefix": prefix,
                    "base": getattr(item, "base_path", None),
                }
                for item, prefix in self._entries
            ],
        }

    def __len__(self) -> int:
        return len(self._entries)

    def __iter__(self) -> Any:
        return iter(self.routers())

    def __repr__(self) -> str:  # pragma: no cover - debugging aid
        return f"<ResourceRegistry name={self.name!r} entries={len(self._entries)}>"