"""Resource / API layer: a thin, declarative resource abstraction on WebRouter.

This module does **not** create a second API framework.  It layers a small,
LLM-friendly declaration surface on top of the existing Betrayer abstractions
(:class:`~betrayer.web.routing.WebRouter`, :class:`~betrayer.web.request.Request`,
:class:`~betrayer.web.response.ApiResponse`, :class:`~betrayer.web.context.WebContext`)
so an application can define resources without inventing a parallel route
system.

What is offered
---------------
* :class:`ApiResource` -- a base class that declares endpoints
  (``method + path + handler``) and registers them on any ``WebRouter``.
* :class:`CrudApiResource` -- one shared CRUD implementation
  (``GET/POST/GET <id>/PUT <id>/DELETE <id>``) that delegates to a service,
  so every resource uses the same flow instead of per-resource special cases.
* :class:`ResourceRegistry` -- collects routers/resources and mounts them all
  on one :class:`~betrayer.web.adapter.FlaskAdapter`.
* :func:`register_web_router` -- mount an existing ``WebRouter`` (for example
  one generated by ``bet make resource`` / ``bet make crud``) on an adapter.

Flow preserved:::

    HTTP Request -> Resource (route handler) -> Service -> Repository/Data

Resources stay thin: they resolve a service through ``WebContext.resolve()``
(the Task 02 container) and never take over business logic.
"""

from __future__ import annotations

from typing import Any, Callable, Iterable, List, Optional, Sequence, Tuple, Union

from betrayer.web.context import WebContext
from betrayer.web.request import Request
from betrayer.web.response import ApiResponse, Response
from betrayer.web.routing import Route, WebRouteRegistry, WebRouter
from betrayer.web.validation import Schema, ValidationResult, validate as _validate

__all__ = [
    "ApiResource",
    "CrudApiResource",
    "ResourceRegistry",
    "register_web_router",
]


def _dumps(item: Any) -> Any:
    """Serialize ``item`` to a plain dict when it exposes ``to_dict``."""
    if hasattr(item, "to_dict"):
        value = item.to_dict()
        return value() if callable(value) else value
    return item


def _collection_response(items: Sequence[Any], *, resource: str) -> Response:
    payload = [_dumps(item) for item in items]
    return ApiResponse.success(
        data=payload,
        meta={"resource": resource, "count": len(payload)},
    )


class ApiResource:
    """Declarative collection of HTTP endpoints bound to one WebRouter.

    Subclasses declare their endpoints by overriding :meth:`endpoints` (or by
    passing ``routes`` to the constructor) and register on any
    :class:`~betrayer.web.routing.WebRouter`::

        class HealthResource(ApiResource):
            name = "health"
            prefix = "/api/v1"

            def endpoints(self):
                return [
                    ("GET", "/ping", self.ping),
                ]

            async def ping(self, request, context):
                return ApiResponse.success({"status": "ok"})

        router = WebRouter(name="app")
        HealthResource().register(router)   # -> GET /api/v1/health/ping

    Handlers use the documented ``handler(request, context) -> Response``
    signature and may be sync or async.  The resource never touches Flask.
    """

    #: Resource identifier used for the default path base (``/{name}``),
    #: the router name and the default service key (``{name}_service``).
    name: str = "resource"

    #: Optional path prefix, e.g. ``"/api/v1"`` (joined without a double slash).
    prefix: str = ""

    #: Declarative ``(method, path, handler)`` triples.  Pass ``None`` and
    #: override :meth:`endpoints` for the explicit form.
    routes: Tuple[Tuple[str, str, Callable[..., Any]], ...] = ()

    #: Optional request validation schema (a
    #: :class:`~betrayer.web.validation.Schema` instance, a ``Schema``
    #: subclass, or a raw field mapping).  When set, the CRUD handlers parse
    #: the JSON body once and validate it *before* calling the service.
    schema: Any = None

    def __init__(
        self,
        *,
        service: Any = None,
        service_key: Optional[str] = None,
    ) -> None:
        self.service = service
        self._service_key = service_key

    # -- declaration ---------------------------------------------------
    @property
    def service_key(self) -> str:
        """Container key the resource resolves its service from."""
        if self._service_key:
            return self._service_key
        return f"{self.name}_service"

    @property
    def base_path(self) -> str:
        """Default path base: ``{prefix}/{name}`` (never a trailing slash)."""
        parts = [str(self.prefix or "").strip("/"), self.name]
        return "/" + "/".join(part for part in parts if part)

    def endpoints(self) -> Sequence[Tuple[str, str, Callable[..., Any]]]:
        """Return ``(method, path, handler)`` endpoint declarations.

        Paths are relative to :attr:`base_path` (``""`` = the collection,
        ``"/<id>"`` = one item).  Override this in subclasses; the default
        returns the class-level :attr:`routes` triples.
        """
        return list(self.routes)

    # -- registration --------------------------------------------------
    def register(
        self,
        router: WebRouter,
        *,
        prefix: Optional[str] = None,
    ) -> List[Route]:
        """Register every endpoint on ``router``; returns the created routes.

        ``prefix`` overrides :attr:`prefix` for this call, so the same
        resource can be mounted at several bases without redefining it.
        """
        base = "/" + "/".join(
            part
            for part in [str(prefix or self.prefix or "").strip("/"), self.name]
            if part
        )
        created: List[Route] = []
        for method, path, handler in self.endpoints():
            full = base + str(path)
            created.append(
                router.add(method, full, handler, module=self.name)
            )
        return created

    def resource_router(self) -> WebRouter:
        """A dedicated ``WebRouter`` for this resource (already registered)."""
        router = WebRouter(name=self.name)
        self.register(router)
        return router

    # -- service resolution -------------------------------------------
    def resolve_service(self, context: WebContext) -> Any:
        """Resolve the service from the container (unless injected).

        ``self.service`` when given wins; otherwise the service is resolved
        from the request ``WebContext`` under :attr:`service_key`.  The
        resolution is lazy so a resource can be unit tested with a plain
        stub instead of a full application.
        """
        if self.service is not None:
            return self.service
        return context.resolve(self.service_key)

    # -- request validation pipeline (Task 11) ------------------------
    def request_schema(self) -> Any:
        """Return the resolved validation ``Schema`` (or ``None``).

        ``self.schema`` (or a ``schema_key`` service on the container) may be a
        :class:`~betrayer.web.validation.Schema` instance, a ``Schema``
        subclass or a raw field mapping; it is normalised here so handlers
        never branch on its shape.
        """
        raw = self.schema
        if raw is None:
            return None
        if isinstance(raw, Schema):
            return raw
        if isinstance(raw, type) and issubclass(raw, Schema):
            return raw()
        if isinstance(raw, dict):
            return Schema(raw)
        from betrayer.web.exceptions import WebAdapterError

        raise WebAdapterError(
            message=(
                "Resource.schema must be a Schema, a Schema subclass or a field "
                f"mapping, got {type(raw).__name__}"
            ),
            code="RESOURCE_SCHEMA_INVALID",
            context={"resource": self.name},
        )

    def validate_request(
        self,
        request: Request,
        context: Optional[WebContext] = None,
        *,
        partial: bool = False,
    ) -> ValidationResult:
        """Parse the body once, validate it, return the structured result.

        The JSON body is read through :meth:`json_body` (memoised, so parsing
        happens exactly once).  When a :attr:`schema` is declared the body is
        validated against it; the :class:`ValidationResult` is attached to the
        ``WebContext`` (``context.validation``) so the Service can read it too.

        An invalid body raises the framework ``ValidationError`` (422
        ``VALIDATION_FAILED``) carrying the structured field errors, so the
        service is never called.
        """
        body = self.json_body(request)
        result = _validate(self.request_schema(), body, partial=partial)
        if context is not None:
            context.set_validation(result)
        result.raise_if_invalid()
        return result

    def validated_body(
        self,
        request: Request,
        context: Optional[WebContext] = None,
        *,
        partial: bool = False,
    ) -> dict:
        """Validated, cleaned payload ready to hand to the service."""
        return self.validate_request(request, context, partial=partial).data

    # -- request/response helpers (thin, no business logic) -----------
    @staticmethod
    def param(request: Request, name: str, *, cast: Callable[[Any], Any] = None) -> Any:
        """Return a path parameter, optionally coerced via ``cast``."""
        value = request.param(name)
        if cast is not None and value is not None:
            return cast(value)
        return value

    @staticmethod
    def query(request: Request, name: str, default: Any = None) -> Any:
        """Return a single query parameter (``default`` when absent)."""
        return request.get_query(name, default)

    @staticmethod
    def json_body(request: Request) -> dict:
        """Return the request JSON body as a dict.

        Raises :class:`~betrayer.web.exceptions.BadRequestError` when the
        body is missing, not JSON, or not a JSON object -- so handlers never
        have to repeat that check.
        """
        from betrayer.web.exceptions import BadRequestError

        body = request.json
        if body is None:
            raise BadRequestError(
                message="Request body must be a JSON object",
                code="BAD_REQUEST",
            )
        if not isinstance(body, dict):
            raise BadRequestError(
                message="Request body must be a JSON object",
                code="BAD_REQUEST",
                context={"content_type": request.content_type},
            )
        return body

    def require_fields(self, request: Request, *names: str) -> dict:
        """Validate that ``names`` are present in the JSON body.

        Returns the body (a dict).  Raises
        :class:`~betrayer.web.exceptions.ValidationError` (422) listing the
        missing fields, using the status code the Betrayer web layer maps a
        validation failure to.
        """
        from betrayer.web.exceptions import ValidationError

        body = self.json_body(request)
        missing = [name for name in names if name not in body]
        if missing:
            raise ValidationError(
                message=f"Missing required field(s): {', '.join(missing)}",
                errors=[{"field": name, "required": True} for name in missing],
            )
        return body

    @staticmethod
    def not_found(message: str = "Resource not found") -> None:
        """Raise :class:`~betrayer.web.exceptions.NotFoundError` (404)."""
        from betrayer.web.exceptions import NotFoundError

        raise NotFoundError(message)

    # -- introspection ------------------------------------------------
    def to_dict(self) -> dict:
        """JSON friendly description of the declared resource."""
        return {
            "type": type(self).__name__,
            "name": self.name,
            "prefix": self.prefix,
            "base_path": self.base_path,
            "service_key": self.service_key,
            "endpoints": [
                {"method": method, "path": self.base_path + path}
                for method, path, _handler in self.endpoints()
            ],
        }

    describe = to_dict

    def __repr__(self) -> str:  # pragma: no cover - debugging aid
        return f"<{type(self).__name__} name={self.name!r} base={self.base_path!r}>"


class CrudApiResource(ApiResource):
    """One shared CRUD implementation for any service.

    Declares the standard REST endpoints and delegates every operation to the
    resolved service (``list``, ``get``, ``create``, ``update``, ``delete``),
    so no resource needs a per-resource copy of the flow::

        class ProductResource(CrudApiResource):
            name = "product"
            prefix = "/api/v1"

        router = WebRouter(name="app")
        ProductResource(service_key="product_service").register(router)

    Endpoints (paths are relative to ``{prefix}/{name}``)::

        GET    ""          -> service.list()        -> 200 [items]
        GET    "/<id>"     -> service.get(id)       -> 200 {item} | 404
        POST   ""          -> service.create(**body) -> 201 {item}
        PUT    "/<id>"     -> service.update(id, **body) -> 200 {item} | 404
        DELETE "/<id>"     -> service.delete(id)    -> 204 | 404

    ``PATCH`` is an alias handled by the same update flow: override
    :attr:`extra_methods` with ``[("PATCH", "/<id>", self.update_handler)]``
    if PATCH is needed; the default route set is deterministic and small.
    """

    #: Routes added on top of the standard CRUD set (e.g. PATCH).
    extra_methods: Tuple[Tuple[str, str, Callable[..., Any]], ...] = ()

    def endpoints(self) -> Sequence[Tuple[str, str, Callable[..., Any]]]:
        standard: List[Tuple[str, str, Callable[..., Any]]] = [
            ("GET", "", self.list_handler),
            ("GET", "/<id>", self.get_handler),
            ("POST", "", self.create_handler),
            ("PUT", "/<id>", self.update_handler),
            ("DELETE", "/<id>", self.delete_handler),
        ]
        return standard + list(self.extra_methods)

    # -- handlers (thin delegation, business logic stays in the service)
    async def list_handler(self, request: Request, context: WebContext) -> Response:
        """GET {base} -- list all items through the service."""
        service = self.resolve_service(context)
        return _collection_response(
            service.list(), resource=self.name
        )

    async def get_handler(self, request: Request, context: WebContext) -> Response:
        """GET {base}/<id> -- fetch one item through the service."""
        service = self.resolve_service(context)
        identifier = request.param("id")
        item = service.get(identifier)
        if item is None:
            self.not_found(f"{self.name} not found")
        return ApiResponse.success(data=_dumps(item))

    async def create_handler(self, request: Request, context: WebContext) -> Response:
        """POST {base} -- validate then create an item through the service."""
        service = self.resolve_service(context)
        body = self.validated_body(request, context)
        item = service.create(**body)
        return ApiResponse.success(
            data=_dumps(item),
            status=201,
            meta={"resource": self.name},
        )

    async def update_handler(self, request: Request, context: WebContext) -> Response:
        """PUT {base}/<id> -- validate (partial) then update through the service."""
        service = self.resolve_service(context)
        identifier = request.param("id")
        body = self.validated_body(request, context, partial=True)
        item = service.update(identifier, **body)
        if item is None:
            self.not_found(f"{self.name} not found")
        return ApiResponse.success(data=_dumps(item))

    async def delete_handler(self, request: Request, context: WebContext) -> Response:
        """DELETE {base}/<id> -- delete an item through the service."""
        service = self.resolve_service(context)
        identifier = request.param("id")
        deleted = service.delete(identifier)
        if not deleted:
            self.not_found(f"{self.name} not found")
        return Response.no_content()

    def __init__(self, *, service: Any = None, service_key: Optional[str] = None) -> None:
        super().__init__(service=service, service_key=service_key)


def register_web_router(
    target: Any,
    router: WebRouter,
    *,
    prefix: str = "",
) -> Any:
    """Mount an existing ``WebRouter`` on a :class:`FlaskAdapter` (or Flask app).

    ``target`` is a :class:`~betrayer.web.adapter.FlaskAdapter` or a Flask
    application.  This is the compatibility helper for routers generated by
    ``bet make resource`` / ``bet make crud`` (Task 07)::

        from betrayer.web.adapter import FlaskAdapter
        from betrayer.web.resource import register_web_router
        from products.routes import router as product_router

        adapter = FlaskAdapter(application)          # build once
        register_web_router(adapter, product_router) # mount a generated router

    Returns the target adapter.
    """
    add = getattr(target, "add_router", None)
    if callable(add):
        add(router, prefix=prefix)
        return target
    # Plain Flask app: wrap it with an adapter and mount.
    from betrayer.web.adapter import FlaskAdapter

    adapter = FlaskAdapter(application=getattr(target, "application", None) or target, app=target)
    adapter.add_router(router, prefix=prefix)
    return adapter


class ResourceRegistry:
    """Collect resources/routers and mount them all on one adapter.

    Avoids route conflicts by letting the caller assign a ``prefix`` per
    entry; every item keeps its own ``WebRouter`` so registration order and
    ownership stay explicit.
    """

    def __init__(self, *, name: str = "resources") -> None:
        self.name = name
        self._entries: List[Tuple[Any, str]] = []

    # -- mutation -----------------------------------------------------
    def add(self, item: Any, *, prefix: str = "") -> "ResourceRegistry":
        """Register ``item`` (a ``WebRouter``, ``WebRouteRegistry`` or
        ``ApiResource``); ``prefix`` is prepended to every route path."""
        self._entries.append((item, (prefix or "").rstrip("/")))
        return self

    register = add

    def clear(self) -> None:
        """Drop every entry (used by tests/tooling)."""
        self._entries.clear()

    # -- access -------------------------------------------------------
    @property
    def entries(self) -> List[Tuple[Any, str]]:
        """Registered ``(item, prefix)`` pairs in registration order."""
        return list(self._entries)

    def routers(self) -> List[WebRouter]:
        """Resolve every entry into a ``WebRouter`` with its prefix applied.

        ``ApiResource`` entries are first registered on their own router;
        plain ``WebRouter`` entries are kept; ``WebRouteRegistry`` entries
        are wrapped.  Prefixes are baked into the returned routers.
        """
        routers: List[WebRouter] = []
        for item, prefix in self._entries:
            if isinstance(item, ApiResource):
                router = item.resource_router()
            elif isinstance(item, WebRouter):
                router = item
            elif isinstance(item, WebRouteRegistry):
                router = WebRouter(routes=item, name=item.name)
            else:
                raise TypeError(
                    "ResourceRegistry accepts ApiResource, WebRouter or "
                    f"WebRouteRegistry, got {type(item).__name__}"
                )
            if prefix:
                prefixed = WebRouter(name=f"{prefix}.{router.name}")
                for route in router.routes.list():
                    prefixed.add(
                        route.method,
                        f"{prefix}{route.path}",
                        route.handler,
                        name=route.endpoint,
                        module=route.module,
                        middleware=list(route.middleware),
                        metadata=dict(route.metadata),
                    )
                router = prefixed
            routers.append(router)
        return routers

    def merge(self, adapter: Any) -> Any:
        """Mount every router on ``adapter`` (a ``FlaskAdapter``)."""
        for router in self.routers():
            adapter.add_router(router)
        return adapter

    # -- introspection ------------------------------------------------
    def to_dict(self) -> dict:
        """JSON friendly snapshot of the registry."""
        return {
            "name": self.name,
            "entries": [
                {
                    "type": type(item).__name__,
                    "prefix": prefix,
                    "base": getattr(item, "base_path", None),
                }
                for item, prefix in self._entries
            ],
        }

    def __len__(self) -> int:
        return len(self._entries)

    def __iter__(self) -> Any:
        return iter(self.routers())

    def __repr__(self) -> str:  # pragma: no cover - debugging aid
        return f"<ResourceRegistry name={self.name!r} entries={len(self._entries)}>"