"""The ``blog`` feature package.

Generated by ``bet make feature blog``.

Public API::

        BlogModel
    BlogRepository
    BlogService
    BlogFeatureModule

Register it on an application::

    from blog import BlogFeatureModule

    app.modules.register(BlogFeatureModule)
"""

from __future__ import annotations

from blog.models import BlogModel
from blog.repository import BlogRepository
from blog.service import BlogService
from blog.module import BlogFeatureModule

__all__ = ['BlogModel', 'BlogRepository', 'BlogService', 'BlogFeatureModule']
