"""The ``blog`` data model.

Generated by ``bet make feature blog``.

Defines the :class:`BlogModel` data structure using the framework's
:class:`betrayer.data.models.Model` and :class:`~betrayer.data.models.Field`
abstractions. Extend with additional fields as needed.
"""

from __future__ import annotations

from datetime import datetime
from typing import Any, Dict

from betrayer.data.models import Field, Model

__all__ = ["BlogModel"]


class BlogModel(Model):
    """Data model for a ``blog`` feature.

    Fields are declared as class-level :class:`~betrayer.data.models.Field`
    instances. This is the single source of truth for the feature's shape.
    """

    # -- metadata (auto-managed) --
    id: int = Field(int, required=True, description="Primary key")
    created_at: datetime = Field(datetime, default=None, description="Creation timestamp")
    updated_at: datetime = Field(datetime, default=None, description="Last update timestamp")

    # -- feature fields (customise as needed) --
    name: str = Field(str, required=True, description="Display name of the blog")

    # -- introspection helpers --

    @classmethod
    def resource_metadata(cls) -> Dict[str, Any]:
        """Return deterministic metadata about this model."""
        return {
            "feature": "blog",
            "model": cls.__name__,
            "fields": [f.to_dict() for f in cls._fields.values()],
            "table": "blogs",
        }
