"""Feature module for ``blog``.

Generated by ``bet make feature blog``.

The feature module integrates all components into the Betrayer module system.
It is the single point of registration for the feature on an application:
components are registered on the container so routes can resolve them.
"""

from __future__ import annotations

from typing import Any, Tuple
from betrayer.core.module import Module
from blog.models import BlogModel
from blog.repository import BlogRepository
from blog.service import BlogService

__all__ = ["BlogFeatureModule"]


class BlogFeatureModule(Module):
    """Betrayer module for the ``blog`` feature.

    Registers components on the application container.
    """

    name = "blog"
    version = "0.1.0"
    dependencies: Tuple[str, ...] = ()
    services: Tuple[str, ...] = ("blog_repository", "blog_service",)
    metadata = {'description': 'the blog feature module', 'model': 'BlogModel', 'repository': 'BlogRepository', 'service': 'BlogService'}

    def register(self, context: Any) -> None:
        """Declare the feature: register components on the container."""
        container = context.container

        def _build_repository() -> BlogRepository:
            database = container.resolve("database")
            return BlogRepository(database=database)

        container.singleton("blog_repository", _build_repository)

        def _build_service() -> BlogService:
            repository = container.resolve("blog_repository")
            return BlogService(repository=repository)

        container.singleton("blog_service", _build_service)


    def initialize(self, context: Any) -> None:
        """Initialize the feature module."""

    def shutdown(self, context: Any) -> None:
        """Tear down the feature module."""
