"""Repository for the ``blog`` feature.

Generated by ``bet make feature blog``.

Provides CRUD operations (:meth:`get`, :meth:`find`, :meth:`list`,
:meth:`create`, :meth:`update`, :meth:`delete`) for the
BlogModel.
"""

from __future__ import annotations

from typing import Any, Dict, Optional

from betrayer.core.container import Container
from betrayer.data.database import DatabaseManager
from betrayer.data.repository import Repository
from blog.models import BlogModel

__all__ = ["BlogRepository"]


class BlogRepository(Repository[BlogModel]):
    """Repository for the ``blog`` feature.

    Extend with feature-specific query methods as needed.
    """

    def __init__(
        self,
        database: DatabaseManager,
        container: Optional[Container] = None,
    ) -> None:
        super().__init__(model_class=BlogModel, database=database, container=container)

    # -- introspection --

    def introspect(self) -> Dict[str, Any]:
        """Machine readable metadata."""
        base = super().introspect()
        base["feature"] = "blog"
        return base
