"""Web routes for the ``blog`` feature.

Generated by ``bet make feature blog``.

Provides standard RESTful endpoints. Handlers use the documented
``handler(request, context)`` signature from :mod:`betrayer.web.routing` and
delegate to the blog service resolved through the ``WebContext`` container.
"""

from __future__ import annotations

from typing import Any

from betrayer.web.context import WebContext
from betrayer.web.request import Request
from betrayer.web.response import ApiResponse, Response
from betrayer.web.routing import WebRouter

__all__ = ["router", "register_routes"]

router = WebRouter(name="blog")


# -- handlers -------------------------------------------------------


async def list_blog(request: Request, context: WebContext) -> Response:
    """GET /blogs -- list all blog resources."""
    service = context.resolve("blog_service")
    items = [item.to_dict() for item in service.list()]
    return ApiResponse.success(data=items, meta={"feature": "blog", "count": len(items)})


async def get_blog(request: Request, context: WebContext) -> Response:
    """GET /blogs/<id> -- retrieve a single blog resource."""
    service = context.resolve("blog_service")
    resource_id = request.param("id")
    item = service.get(resource_id)
    if item is None:
        return ApiResponse.error("RESOURCE_NOT_FOUND", "blog not found", status=404)
    return ApiResponse.success(data=item.to_dict())


async def create_blog(request: Request, context: WebContext) -> Response:
    """POST /blogs -- create a new blog resource."""
    service = context.resolve("blog_service")
    item = service.create(**request.json)
    return ApiResponse.success(data=item.to_dict(), status=201)


async def update_blog(request: Request, context: WebContext) -> Response:
    """PUT /blogs/<id> -- update an existing blog resource."""
    service = context.resolve("blog_service")
    resource_id = request.param("id")
    item = service.update(resource_id, **request.json)
    if item is None:
        return ApiResponse.error("RESOURCE_NOT_FOUND", "blog not found", status=404)
    return ApiResponse.success(data=item.to_dict())


async def delete_blog(request: Request, context: WebContext) -> Response:
    """DELETE /blogs/<id> -- delete a blog resource."""
    service = context.resolve("blog_service")
    resource_id = request.param("id")
    deleted = service.delete(resource_id)
    if not deleted:
        return ApiResponse.error("RESOURCE_NOT_FOUND", "blog not found", status=404)
    return Response.no_content()


# -- registration ---------------------------------------------------


def register_routes(web_router: WebRouter, prefix: str = "") -> None:
    """Register all feature routes on an existing ``WebRouter``.

    Args:
        web_router: The target router to register routes on.
        prefix: Optional path prefix (e.g. ``"/api/v1"``).
    """
    base = f"{prefix}/blogs"
    web_router.get(base, list_blog)
    web_router.get("{base}/<id>", get_blog)
    web_router.post(base, create_blog)
    web_router.put("{base}/<id>", update_blog)
    web_router.delete("{base}/<id>", delete_blog)
