"""Business service for the ``blog`` feature.

Generated by ``bet make feature blog``.

The service sits between the web handlers and the repository: handlers stay
thin and delegates to this class, which owns the business logic for the
``blog`` feature. It is resolved from the application container under the
name ``blog_service``.
"""

from __future__ import annotations

from typing import Any, Dict, Optional, Sequence
from blog.repository import BlogRepository

__all__ = ["BlogService"]


class BlogService:
    """Business service for the ``blog`` feature.

    ``repository`` is injected (resolved from the framework container) so this
    class stays unit-testable without web or database wiring.
    """

    name = "blog_service"

    def __init__(self, repository: BlogRepository) -> None:
        self._repository = repository

    @property
    def repository(self) -> BlogRepository:
        """The underlying repository instance."""
        return self._repository

    # -- CRUD operations (thin, explicit delegation) --

    def get(self, identifier: Any) -> Optional[Any]:
        """Retrieve a single record by primary identifier."""
        return self._repository.get(identifier)

    def find(self, **filters: Any) -> Sequence[Any]:
        """Find records matching the given field/value filters."""
        return self._repository.find(**filters)

    def list(self) -> Sequence[Any]:
        """Return all records for the managed feature."""
        return self._repository.list()

    def create(self, **data: Any) -> Any:
        """Create a new record from ``data``."""
        model_class = self._repository.model_class
        model = model_class.from_dict(data)
        return self._repository.create(model)

    def update(self, identifier: Any, **data: Any) -> Any:
        """Update the record ``identifier`` with ``data``."""
        model = self._repository.get(identifier)
        if model is None:
            return None
        for key, value in data.items():
            setattr(model, key, value)
        return self._repository.update(model)

    def delete(self, identifier: Any) -> bool:
        """Delete a record by identifier. Returns True if deleted."""
        return self._repository.delete(identifier)

    # -- introspection --

    def introspect(self) -> Dict[str, Any]:
        """Machine readable metadata."""
        return {
            "type": "service",
            "name": self.name,
            "class": type(self).__name__,
            "feature": "blog",
            "repository": "BlogRepository",
        }
