"""Module generator for the Betrayer Framework.

Creates a new application module inside an existing BetLayer project.  A
module is the structural unit defined by :class:`betrayer.core.module.Module`:
a small, importable Python package that declares its name, dependencies and
lifecycle hooks (``register`` / ``initialize`` / ``shutdown``) and is attached
to an application through ``app.modules.register(...)``.

The generator deliberately produces *only* that structure -- the real module
contract from ``betrayer.core.module`` -- and nothing else.  It does not invent
controllers, services, repositories or models; those belong to the resource /
service / CRUD generators (later tasks).

Scope: this generator ONLY creates a module skeleton.  It reuses the exact
abstractions the framework already provides (``BaseGenerator``, ``GeneratorError``,
``GeneratorOutput`` and the naming helpers in ``betrayer.generators.base``).

Example usage::

    bet make module users
    bet make module audit_log --force
"""

from __future__ import annotations

from pathlib import Path
from typing import Dict, Optional

from betrayer.generators.base import (
    BaseGenerator,
    GeneratorError,
    GeneratorOutput,
    package_name,
    title_case,
    validate_project_name,
)

__all__ = ["ModuleGenerator", "validate_module_name", "MODULE_VERSION"]

#: Initial version assigned to a freshly generated module.
MODULE_VERSION = "0.1.0"


def validate_module_name(name: str) -> Optional[str]:
    """Return a human readable error message, or ``None`` when ``name`` is OK.

    Module names follow the same convention as project names (letters, digits,
    ``-`` and ``_``; must start with a letter) so the CLI surface stays
    consistent.  The message is phrased in terms of a *module* though.
    """
    error = validate_project_name(name)
    if error:
        return error.replace("project name", "module name")
    return None


class ModuleGenerator(BaseGenerator):
    """Generate a new application module package.

    ``name`` is the name chosen on the command line; the importable package is
    the ``snake_case`` form of ``name`` (so ``bet make module audit-log``
    produces ``audit_log/``).  The generated :class:`~betrayer.core.module.Module`
    subclass is named ``<TitleCase>Module`` (``audit_log`` -> ``AuditLogModule``).
    """

    name = "module"
    description = "Create a new application module inside the current project"

    def __init__(
        self,
        name: str,
        output_dir: Path,
        overwrite: bool = False,
    ) -> None:
        error = validate_module_name(name)
        if error:
            raise GeneratorError(f"invalid module name: {error}")
        self.requested_name = name
        self.package = package_name(name)
        super().__init__(output_dir=Path(output_dir) / self.package, overwrite=overwrite)

    @property
    def target(self) -> Path:
        """The directory the new module package is created in."""
        return self.output_dir

    @property
    def module_name(self) -> str:
        """The module's ``name`` attribute (its importable package name)."""
        return self.package

    @property
    def class_name(self) -> str:
        """Name of the generated :class:`~betrayer.core.module.Module` subclass."""
        return f"{title_case(self.package)}Module"

    # ── structure ──────────────────────────────────────────────

    def _files(self) -> Dict[str, str]:
        """Deterministic mapping of relative path -> file content."""
        return {
            "__init__.py": self._init_py(),
            "module.py": self._module_py(),
        }

    def _init_py(self) -> str:
        return f'''"""The ``{self.module_name}`` module package.

Generated by ``bet make module {self.requested_name}``.

Public API::

    {self.class_name}    the application module (a ``Module`` subclass)

Register it on an application::

    from {self.module_name} import {self.class_name}

    app.modules.register({self.class_name})
"""

from __future__ import annotations

from {self.module_name}.module import {self.class_name}

__all__ = ["{self.class_name}"]
'''

    def _module_py(self) -> str:
        return f'''"""The ``{self.module_name}`` module of a BetLayer application.

Generated by ``bet make module {self.requested_name}``.

A module is the structural unit of a BetLayer application: it declares a
name, its dependencies and its lifecycle hooks.  It is attached to an
application through the module registry::

    from {self.module_name} import {self.class_name}

    app.modules.register({self.class_name})

Hooks are optional and default to a no-op; fill in only what the module
really needs.  See ``betrayer.core.module`` for the full module contract.
"""

from __future__ import annotations

from typing import Any, Tuple

from betrayer.core.module import Module

__all__ = ["{self.class_name}"]


class {self.class_name}(Module):
    """The ``{self.module_name}`` application module."""

    name = "{self.module_name}"
    version = "{MODULE_VERSION}"
    dependencies: Tuple[str, ...] = ()
    services: Tuple[str, ...] = ()
    metadata = {{"description": "the {self.module_name} module"}}

    def register(self, context: Any) -> None:
        """Declare the module: register providers, components and events."""

    def initialize(self, context: Any) -> None:
        """Run after Foundation bootstrap; may use already built services."""

    def shutdown(self, context: Any) -> None:
        """Release module resources (runs in reverse registration order)."""
'''

    # ── generation ─────────────────────────────────────────────

    def generate(self) -> GeneratorOutput:
        """Create the module package and every generated file.

        Raises :class:`GeneratorError` when the target already exists and is not
        empty and ``overwrite`` is False, so an existing module is never
        overwritten silently.
        """
        if not self.overwrite and self._target_occupied():
            raise GeneratorError(
                "module already exists (use --force to overwrite): "
                f"{self.output_dir}"
            )
        self._ensure_directory(self.output_dir)
        for relative, content in self._files().items():
            try:
                self._write(relative, content)
            except GeneratorError as exc:  # pragma: no cover - defensive
                self.output.add_error(relative, exc)
        return self.output

    def _target_occupied(self) -> bool:
        """True when the target directory exists and is not empty."""
        if not self.output_dir.exists():
            return False
        try:
            return any(self.output_dir.iterdir())
        except OSError:
            return True
