"""Project generator for Betrayer Framework.

Creates a minimal Betrayer application structure with:
- app.py - main application file
- templates/ directory
- tests/ directory
- README.md
- .gitignore
"""

from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING, Dict, List, Optional, Tuple

from betrayer.generators.base import GeneratorResult, TemplateGenerator

if TYPE_CHECKING:
    from ..main import CliContext


class ProjectGenerator(TemplateGenerator):
    """Generate a new Betrayer application project."""

    def __init__(self, context: CliContext, output_dir: Path, overwrite: bool = False):
        super().__init__(context, output_dir)
        self.overwrite = overwrite

    def generate(self) -> GeneratorResult:
        """Create minimal Betrayer project structure.

        Returns:
            GeneratorResult with created/updated/skipped files and errors.
        """
        result = GeneratorResult()

        # Define the minimal structure to create
        files_to_create = self._define_project_structure()

        for rel_path, content in files_to_create.items():
            target_path = self.output_dir / rel_path
            try:
                # Check if file exists
                if target_path.exists():
                    if self.overwrite:
                        target_path.write_text(content)
                        result.updated.append(str(rel_path))
                    else:
                        result.errors.append(
                            f"File already exists: {rel_path} (use --force to overwrite)"
                        )
                        continue

                # Create parent directories
                target_path.parent.mkdir(parents=True, exist_ok=True)
                target_path.write_text(content)
                result.created.append(str(rel_path))
            except OSError as e:
                result.errors.append(f"Failed to create {rel_path}: {e}")

        return result

    def _define_project_structure(
        self, app_name: str
    ) -> Dict[str, str]:
        """Define minimal project structure for Betrayer application."""
        files = {}

        # Main application file
        files["app.py"] = self._generate_app_py(app_name)

        # Templates directory (empty but exists)
        # templates/ is just a placeholder - no actual template files needed yet

        # Tests directory with basic test structure
        files["tests/__init__.py"] = ""
        files["tests/test_app.py"] = self._generate_test_app_py()

        # README.md
        files["README.md"] = self._generate_readme(app_name)

        # .gitignore
        files[".gitignore"] = self._generate_gitignore()

        return files

    def _generate_app_py(self, app_name: str) -> str:
        """Generate main application file."""
        return f'''"""{app_name.capitalize()} - A Betrayer application.

This is a minimal Betrayer application generated by the framework CLI.
Run with: python run.py
"""

from __future__ import annotations


def main() -> int:
    """Main entry point for the application."""
    print(f"Welcome to {app_name}!")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
'''

    def _generate_test_app_py(self) -> str:
        """Generate basic test file for app."""
        return '''"""Basic tests for the application."""

from __future__ import annotations


def test_main_returns_zero() -> None:
    """Test that main returns 0 on success."""
    from app import main

    assert main() == 0
'''

    def _generate_readme(self, app_name: str) -> str:
        """Generate README.md file."""
        return f'''# {app_name.capitalize()}

A minimal Betrayer application.

## Getting Started

```bash
python run.py
```

## Structure

- `app.py` - Main application entry point
- `templates/` - Template files directory
- `tests/` - Test files

## Betrayer Framework

This application is built using the Betrayer Framework. Learn more at:
https://github.com/betrayer/betrayer
'''

    def _generate_gitignore(self) -> str:
        """Generate .gitignore file."""
        return '''# Python
__pycache__/
*.py[cod]
*$py.class
*.so
.Python
build/
develop-eggs/
dist/
downloads/
eggs/
.eggs/
lib/
lib64/
parts/
sdist/
var/
wheels/
*.egg-info/
.installed.cfg
*.egg

# Virtual environments
venv/
ENV/
env/

# IDE
.vscode/
.idea/
*.swp
*.swo
*~

# Environment variables
.env
.env.local

# Runtime data
pids/
*.pid
*.seed
*.pid.lock

# Coverage
.coverage
htmlcov/
.pytest_cache/
.tox/

# Temporary files
tmp/
temp/
*.tmp

# OS files
.DS_Store
Thumbs.db
'''
