"""Resource generator for the Betrayer Framework.

Creates a new data resource package inside an existing Betrayer project.  A
resource is a RESTful data entity that combines a :class:`betrayer.data.models.Model`
(data structure), a :class:`betrayer.data.repository.Repository` (CRUD operations),
and optionally web routes (:class:`betrayer.web.routing.WebRouter`) — all
integrated with a :class:`betrayer.core.module.Module`.

The generator produces the full stack (model → repository → routes → module)
so the generated resource is immediately usable in a Betrayer application.

Example usage::

    bet make resource user
    bet make resource product --force
    bet make resource blog-post --json
"""

from __future__ import annotations

from pathlib import Path
from typing import Dict, Optional

from betrayer.generators.base import (
    BaseGenerator,
    GeneratorError,
    GeneratorOutput,
    package_name,
    title_case,
    validate_project_name,
)

__all__ = ["ResourceGenerator", "validate_resource_name", "RESOURCE_VERSION"]

#: Initial version assigned to a freshly generated resource.
RESOURCE_VERSION = "0.1.0"


def validate_resource_name(name: str) -> Optional[str]:
    """Return a human readable error message, or ``None`` when ``name`` is OK.

    Resource names follow the same convention as project names (letters, digits,
    ``-`` and ``_``; must start with a letter) so the CLI surface stays
    consistent.  The message is phrased in terms of a *resource* though.
    """
    error = validate_project_name(name)
    if error:
        return error.replace("project name", "resource name")
    return None


class ResourceGenerator(BaseGenerator):
    """Generate a new data resource package.

    ``name`` is the name chosen on the command line; the importable package is
    the ``snake_case`` form of ``name`` (so ``bet make resource blog-post``
    produces ``blog_post/``).  The generated :class:`~betrayer.data.models.Model`
    subclass is named ``<TitleCase>Model``, the
    :class:`~betrayer.data.repository.Repository` subclass is named
    ``<TitleCase>Repository``, and the
    :class:`~betrayer.core.module.Module` subclass is named
    ``<TitleCase>ResourceModule``.
    """

    name = "resource"
    description = "Create a new data resource (model + repository + routes) in the current project"

    def __init__(
        self,
        name: str,
        output_dir: Path,
        overwrite: bool = False,
    ) -> None:
        error = validate_resource_name(name)
        if error:
            raise GeneratorError(f"invalid resource name: {error}")
        self.requested_name = name
        self.package = package_name(name)
        super().__init__(output_dir=Path(output_dir) / self.package, overwrite=overwrite)

    @property
    def target(self) -> Path:
        """The directory the new resource package is created in."""
        return self.output_dir

    @property
    def resource_name(self) -> str:
        """The resource's package name (snake_case)."""
        return self.package

    @property
    def model_class_name(self) -> str:
        """Name of the generated :class:`~betrayer.data.models.Model` subclass."""
        return f"{title_case(self.package)}Model"

    @property
    def repository_class_name(self) -> str:
        """Name of the generated :class:`~betrayer.data.repository.Repository` subclass."""
        return f"{title_case(self.package)}Repository"

    @property
    def module_class_name(self) -> str:
        """Name of the generated :class:`~betrayer.core.module.Module` subclass."""
        return f"{title_case(self.package)}ResourceModule"

    @property
    def table_name(self) -> str:
        """Pluralised database table name convention."""
        pkg = self.package
        if pkg.endswith("s"):
            return f"{pkg}es"
        if pkg.endswith("y"):
            return f"{pkg[:-1]}ies"
        return f"{pkg}s"

    # ── structure ──────────────────────────────────────────────

    def _files(self) -> Dict[str, str]:
        """Deterministic mapping of relative path -> file content."""
        return {
            "__init__.py": self._init_py(),
            "models.py": self._models_py(),
            "repository.py": self._repository_py(),
            "routes.py": self._routes_py(),
            "module.py": self._module_py(),
        }

    def _init_py(self) -> str:
        return f'''"""The ``{self.resource_name}`` resource package.

Generated by ``bet make resource {self.requested_name}``.

Public API::

    {self.model_class_name}            the data model (a ``Model`` subclass)
    {self.repository_class_name}       the repository (a ``Repository`` subclass)
    {self.module_class_name}           the resource module (a ``Module`` subclass)
    router                             the ``WebRouter`` with CRUD routes

Register it on an application::

    from {self.resource_name} import {self.module_class_name}

    app.modules.register({self.module_class_name})
"""

from __future__ import annotations

from {self.resource_name}.models import {self.model_class_name}
from {self.resource_name}.repository import {self.repository_class_name}
from {self.resource_name}.module import {self.module_class_name}

__all__ = [
    "{self.model_class_name}",
    "{self.repository_class_name}",
    "{self.module_class_name}",
]
'''

    def _models_py(self) -> str:
        pkg = self.package
        cls = self.model_class_name
        table = self.table_name
        return f'''"""The ``{pkg}`` data model.

Generated by ``bet make resource {self.requested_name}``.

Defines the :class:`{cls}` data structure using the framework's
:class:`betrayer.data.models.Model` and :class:`~betrayer.data.models.Field`
abstractions.  Extend with additional fields as needed.
"""

from __future__ import annotations

from datetime import datetime
from typing import Any, Dict, Optional

from betrayer.data.models import Field, Model

__all__ = ["{cls}"]


class {cls}(Model):
    """Data model for a ``{pkg}`` resource.

    Fields are declared as class-level :class:`~betrayer.data.models.Field`
    instances.  This is the single source of truth for the resource's shape.
    """

    # -- metadata (auto-managed) --
    id: int = Field(int, required=True, description="Primary key")
    created_at: datetime = Field(datetime, default=None, description="Creation timestamp")
    updated_at: datetime = Field(datetime, default=None, description="Last update timestamp")

    # -- resource fields (customise as needed) --
    name: str = Field(str, required=True, description="Display name of the {pkg}")
    description: str = Field(str, default="", description="Optional description")

    # -- introspection helpers --

    @classmethod
    def resource_metadata(cls) -> Dict[str, Any]:
        """Return deterministic metadata about this resource model."""
        return {{
            "resource": "{pkg}",
            "model": cls.__name__,
            "fields": [f.to_dict() for f in cls._fields.values()],
            "table": "{table}",
        }}
'''

    def _repository_py(self) -> str:
        pkg = self.package
        model_cls = self.model_class_name
        repo_cls = self.repository_class_name
        return f'''"""Repository for the ``{pkg}`` resource.

Generated by ``bet make resource {self.requested_name}``.

Provides CRUD operations (:meth:`get`, :meth:`find`, :meth:`list`,
:meth:`create`, :meth:`update`, :meth:`delete`) for the
:class:`{model_cls}` model.
"""

from __future__ import annotations

from typing import Any, Dict, List, Optional, Sequence

from betrayer.core.container import Container
from betrayer.data.database import DatabaseManager
from betrayer.data.exceptions import RepositoryError
from betrayer.data.repository import Repository
from {self.resource_name}.models import {model_cls}

__all__ = ["{repo_cls}"]


class {repo_cls}(Repository[{model_cls}]):
    """CRUD repository for the ``{pkg}`` resource.

    Extend with resource-specific query methods as needed.
    """

    def __init__(
        self,
        database: DatabaseManager,
        container: Optional[Container] = None,
    ) -> None:
        super().__init__(model_class={model_cls}, database=database, container=container)

    # -- introspection --

    def introspect(self) -> Dict[str, Any]:
        """Machine readable metadata."""
        base = super().introspect()
        base["resource"] = "{pkg}"
        return base
'''

    def _routes_py(self) -> str:
        pkg = self.package
        table = self.table_name
        return f'''"""Web routes for the ``{pkg}`` resource.

Generated by ``bet make resource {self.requested_name}``.

Provides standard RESTful CRUD endpoints integrated with the Betrayer
web layer (:class:`betrayer.web.routing.WebRouter`).

Import the :data:`router` instance and register it on the application's
web adapter::

    from {self.resource_name}.routes import register_routes

    register_routes(web_router)   # populates the routes
"""

from __future__ import annotations

from typing import Any

from betrayer.web.request import Request
from betrayer.web.response import ApiResponse, Response
from betrayer.web.routing import WebRouter

__all__ = ["router", "register_routes"]

router = WebRouter(name="{pkg}")


# -- handlers -------------------------------------------------------


async def list_{pkg}(request: Request) -> Response:
    """GET /{table} -- list all {pkg} resources."""
    return ApiResponse.success(data=[], meta={{"resource": "{pkg}", "count": 0}})


async def get_{pkg}(request: Request) -> Response:
    """GET /{table}/<id> -- retrieve a single {pkg} resource."""
    resource_id = request.param("id")
    return ApiResponse.success(data={{"id": resource_id}})


async def create_{pkg}(request: Request) -> Response:
    """POST /{table} -- create a new {pkg} resource."""
    return ApiResponse.success(data=request.json, status=201)


async def update_{pkg}(request: Request) -> Response:
    """PUT /{table}/<id> -- update an existing {pkg} resource."""
    resource_id = request.param("id")
    return ApiResponse.success(data={{"id": resource_id, **request.json}})


async def delete_{pkg}(request: Request) -> Response:
    """DELETE /{table}/<id> -- delete a {pkg} resource."""
    resource_id = request.param("id")
    return Response.no_content()


# -- registration ---------------------------------------------------


def register_routes(web_router: WebRouter, prefix: str = "") -> None:
    """Register all resource routes on an existing ``WebRouter``.

    Args:
        web_router: The target router to register routes on.
        prefix: Optional path prefix (e.g. ``"/api/v1"``).
    """
    base = f"{{prefix}}/{table}"
    web_router.get(base, list_{pkg})
    web_router.get(f"{{base}}/<id>", get_{pkg})
    web_router.post(base, create_{pkg})
    web_router.put(f"{{base}}/<id>", update_{pkg})
    web_router.delete(f"{{base}}/<id>", delete_{pkg})
'''

    def _module_py(self) -> str:
        pkg = self.package
        model_cls = self.model_class_name
        repo_cls = self.repository_class_name
        module_cls = self.module_class_name
        return f'''"""Resource module for ``{pkg}``.

Generated by ``bet make resource {self.requested_name}``.

The resource module integrates the :class:`{model_cls}`, :class:`{repo_cls}`
and web routes into the Betrayer module system.  It is the single point of
registration for the resource on an application.
"""

from __future__ import annotations

from typing import Any, Tuple

from betrayer.core.module import Module

from {self.resource_name}.models import {model_cls}
from {self.resource_name}.repository import {repo_cls}

__all__ = ["{module_cls}"]


class {module_cls}(Module):
    """Betrayer module for the ``{pkg}`` resource.

    Registers the model, repository and related services on the application.
    """

    name = "{pkg}"
    version = "{RESOURCE_VERSION}"
    dependencies: Tuple[str, ...] = ()
    services: Tuple[str, ...] = ("{pkg}_repository",)
    metadata = {{
        "description": "the {pkg} resource module",
        "model": "{model_cls}",
        "repository": "{repo_cls}",
    }}

    def register(self, context: Any) -> None:
        """Declare the resource: register the repository as a service."""
        container = context.container

        def _build_repository() -> {repo_cls}:
            database = container.resolve("database")
            return {repo_cls}(database=database)

        container.singleton("{pkg}_repository", _build_repository)

    def initialize(self, context: Any) -> None:
        """Initialise the resource module."""

    def shutdown(self, context: Any) -> None:
        """Tear down the resource module."""
'''

    # ── generation ─────────────────────────────────────────────

    def generate(self) -> GeneratorOutput:
        """Create the resource package and every generated file.

        Raises :class:`GeneratorError` when the target already exists and is
        not empty and ``overwrite`` is False, so an existing resource is never
        overwritten silently.
        """
        if not self.overwrite and self._target_occupied():
            raise GeneratorError(
                "resource already exists (use --force to overwrite): "
                f"{self.output_dir}"
            )
        self._ensure_directory(self.output_dir)
        for relative, content in self._files().items():
            try:
                self._write(relative, content)
            except GeneratorError as exc:  # pragma: no cover - defensive
                self.output.add_error(relative, exc)
        return self.output

    def _target_occupied(self) -> bool:
        """True when the target directory exists and is not empty."""
        if not self.output_dir.exists():
            return False
        try:
            return any(self.output_dir.iterdir())
        except OSError:
            return True