"""Service generator for the Betrayer Framework.

Creates a new application service inside an existing BetLayer project.  A
service is a plain business-logic class that is registered in the framework's
dependency injection container (:class:`betrayer.core.container.Container`)
under a stable, LLM readable name (``<name>_service``).

The generator deliberately follows the exact convention of the module and
resource generators: a ``snake_case`` package named after the service, a
``<TitleCase>Service`` class and a ``<TitleCase>ServiceModule``
(:class:`~betrayer.core.module.Module` subclass) that registers the service
on the application's container.

Example usage::

    bet make service user
    bet make service notification --force
    bet make service audit-log --json
"""

from __future__ import annotations

from pathlib import Path
from typing import Dict, Optional

from betrayer.generators.base import (
    BaseGenerator,
    GeneratorError,
    GeneratorOutput,
    package_name,
    title_case,
    validate_project_name,
)

__all__ = ["ServiceGenerator", "validate_service_name", "SERVICE_VERSION"]

#: Initial version assigned to a freshly generated service module.
SERVICE_VERSION = "0.1.0"


def validate_service_name(name: str) -> Optional[str]:
    """Return a human readable error message, or ``None`` when ``name`` is OK.

    Service names follow the same convention as project / module / resource
    names (letters, digits, ``-`` and ``_``; must start with a letter) so the
    CLI surface stays consistent.  The message is phrased in terms of a
    *service* though.
    """
    error = validate_project_name(name)
    if error:
        return error.replace("project name", "service name")
    return None


class ServiceGenerator(BaseGenerator):
    """Generate a new application service package.

    ``name`` is the name chosen on the command line; the importable package is
    the ``snake_case`` form of ``name + '_service'`` (so ``bet make service
    user`` produces ``user_service/``).  The generated service class is named
    ``<TitleCase>Service`` (``user`` -> ``UserService``) and the generated
    :class:`~betrayer.core.module.Module` subclass is named
    ``<TitleCase>ServiceModule`` (``user`` -> ``UserServiceModule``).  The
    service is registered on the application container under
    ``<snake_case>_service`` (``user`` -> ``user_service``).
    """

    name = "service"
    description = "Create a new application service in the current project"

    def __init__(
        self,
        name: str,
        output_dir: Path,
        overwrite: bool = False,
    ) -> None:
        error = validate_service_name(name)
        if error:
            raise GeneratorError(f"invalid service name: {error}")
        self.requested_name = name
        self.package = package_name(name)
        super().__init__(
            output_dir=Path(output_dir) / f"{self.package}_service",
            overwrite=overwrite,
        )

    @property
    def target(self) -> Path:
        """The directory the new service package is created in."""
        return self.output_dir

    @property
    def service_name(self) -> str:
        """The service's importable package name (``user`` -> ``user_service``)."""
        return f"{self.package}_service"

    @property
    def service_key(self) -> str:
        """The container service name (``user`` -> ``user_service``)."""
        return f"{self.package}_service"

    @property
    def service_class_name(self) -> str:
        """Name of the generated service class (``user`` -> ``UserService``)."""
        return f"{title_case(self.package)}Service"

    @property
    def module_class_name(self) -> str:
        """Name of the generated :class:`~betrayer.core.module.Module` subclass."""
        return f"{title_case(self.package)}ServiceModule"

    # ── structure ──────────────────────────────────────────────────────

    def _files(self) -> Dict[str, str]:
        """Deterministic mapping of relative path -> file content."""
        return {
            "__init__.py": self._init_py(),
            "service.py": self._service_py(),
            "module.py": self._module_py(),
        }

    def _init_py(self) -> str:
        service_cls = self.service_class_name
        module_cls = self.module_class_name
        return f'''"""The ``{self.service_name}`` service package.

Generated by ``bet make service {self.requested_name}``.

Public API::

    {service_cls}   the service class (plain business logic)
    {module_cls}    the service module (a ``Module`` subclass)

Register it on an application::

    from {self.service_name} import {module_cls}

    app.modules.register({module_cls})
"""

from __future__ import annotations

from {self.service_name}.module import {module_cls}
from {self.service_name}.service import {service_cls}

__all__ = ["{service_cls}", "{module_cls}"]
'''

    def _service_py(self) -> str:
        service_cls = self.service_class_name
        return f'''"""The ``{self.service_name}`` application service.

Generated by ``bet make service {self.requested_name}``.

A service is a plain class holding business logic; it is resolved from the
application container (``container.resolve("{self.service_key}")``) instead of
being instantiated by callers.  Add your domain methods here and declare
container dependencies in the module (``betrayer.core.module.Module``).
"""

from __future__ import annotations

from typing import Any, Dict

__all__ = ["{service_cls}"]


class {service_cls}:
    """Business service for ``{self.service_name}``.

    Instances are built by the container provider registered in
    :class:`{self.module_class_name}`.
    """

    name = "{self.service_key}"

    def introspect(self) -> Dict[str, Any]:
        """Machine readable metadata for LLM inspection."""
        return {{
            "type": "service",
            "name": self.name,
            "class": type(self).__name__,
        }}

    def __repr__(self) -> str:  # pragma: no cover - debugging aid
        return f"<{{type(self).__name__}} name={{self.name!r}}>"
'''

    def _module_py(self) -> str:
        service_cls = self.service_class_name
        module_cls = self.module_class_name
        return f'''"""Service module for ``{self.service_name}``.

Generated by ``bet make service {self.requested_name}``.

The service module registers the :class:`{service_cls}` on the application's
dependency injection container under the name ``{self.service_key}``, so web
handlers and other services can resolve it through
``context.resolve("{self.service_key}")``.
"""

from __future__ import annotations

from typing import Any, Tuple

from betrayer.core.module import Module

from {self.service_name}.service import {service_cls}

__all__ = ["{module_cls}"]


class {module_cls}(Module):
    """BetLayer module for the ``{self.service_name}`` service.

    Registers the service on the application container.
    """

    name = "{self.service_name}"
    version = "{SERVICE_VERSION}"
    dependencies: Tuple[str, ...] = ()
    services: Tuple[str, ...] = ("{self.service_key}",)
    metadata = {{
        "description": "the {self.service_name} service module",
        "service": "{self.service_key}",
        "class": "{service_cls}",
    }}

    def register(self, context: Any) -> None:
        """Declare the service: register it on the container."""
        container = context.container

        def _build_{self.package}_service() -> {service_cls}:
            return {service_cls}()

        container.singleton("{self.service_key}", _build_{self.package}_service)

    def initialize(self, context: Any) -> None:
        """Initialise the service module."""

    def shutdown(self, context: Any) -> None:
        """Tear down the service module."""
'''

    # ── generation ──────────────────────────────────────────────────────

    def generate(self) -> GeneratorOutput:
        """Create the service package and every generated file.

        Raises :class:`GeneratorError` when the target already exists and is
        not empty and ``overwrite`` is False, so an existing service is never
        overwritten silently.
        """
        if not self.overwrite and self._target_occupied():
            raise GeneratorError(
                "service already exists (use --force to overwrite): "
                f"{self.output_dir}"
            )
        self._ensure_directory(self.output_dir)
        for relative, content in self._files().items():
            try:
                self._write(relative, content)
            except GeneratorError as exc:  # pragma: no cover - defensive
                self.output.add_error(relative, exc)
        return self.output

    def _target_occupied(self) -> bool:
        """True when the target directory exists and is not empty."""
        if not self.output_dir.exists():
            return False
        try:
            return any(self.output_dir.iterdir())
        except OSError:
            return True